name: Github Pages

on:
  # Runs when a release is published
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build & Deploy Job
  gh_pages:
    name: Build & Deploy Github Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.gh_pages.outputs.page_url }}
    env:
      GHP_SOURCE_DIR: gh_pages_source
      GHP_ITEMS_FILE: github-pages-items.txt
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gather items for Github Pages
        run: |
          mkdir $GHP_SOURCE_DIR
          cat $GHP_ITEMS_FILE | xargs -I % cp % $GHP_SOURCE_DIR
      - name: Build & Deploy
        id: gh_pages
        uses: dunkmann00/jekyll-v4-gh-pages@v1
        with:
          source: ${{ env.GHP_SOURCE_DIR }}
